name: fist

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & PushImage
      run: |
        echo "${{secrets.DOCKERPW}}" | docker login -u "gitlaptry1" --password-stdin
        docker image build -t gitlaptry1/douckertry:fist
        docker push gitlaptry1/douckertry:fist
